In [35]:
con.close()

In [27]:
import duckdb

con = duckdb.connect(r"C:\data\my_warehouse.duckdb", read_only=True)

# List all tables and views
df_objects = con.execute("""
    SELECT table_schema, table_name, table_type 
    FROM information_schema.tables 
    WHERE table_schema NOT IN ('information_schema', 'pg_catalog')
    ORDER BY table_type, table_name;
""").df()

print(df_objects)
# con.close()

   table_schema                  table_name table_type
0          main           Purchases_Invoice       VIEW
1          main          Purchases_Invoices       VIEW
2          main                Sale_Invoice       VIEW
3          main              dimension_city       VIEW
4          main          dimension_customer       VIEW
5          main              dimension_date       VIEW
6          main          dimension_employee       VIEW
7          main    dimension_payment_method       VIEW
8          main        dimension_stock_item       VIEW
9          main          dimension_supplier       VIEW
10         main  dimension_transaction_type       VIEW
11         main               fact_movement       VIEW
12         main                  fact_order       VIEW
13         main               fact_purchase       VIEW
14         main                   fact_sale       VIEW
15         main          fact_stock_holding       VIEW
16         main            fact_transaction       VIEW

In [29]:
Purchases_Invoice = con.execute("SELECT * FROM Purchases_Invoice limit 20").df()
display(Purchases_Invoice)

,Purchase Number,Purchased or Order Dates,Purchased or Order Day Number,Purchased or Order Day,Purchased or Order Month Name,Purchased or Order Short Month Name,Purchased or Order Month Number,Purchased or Order Calendar Month Name,Purchased or Order Year Number,Purchased or Order Calendar Year Name,...,Item Barcode,Item Tax Rate,Item Unit Price,Item Recommended Retail Price,Item Typical Weight Per Unit,Ordered Outers,Ordered Quantity,Received Outers,Purchases Package,Is Purchases Finalized
0,1404,2015-04-28,28,28,April,Apr,4,CY2015-Apr,2015,CY2015,...,N/A,7.0,18.0,26.91,0.25,2300,27600,2300,Carton,True
1,2032,2016-05-05,5,5,May,May,5,CY2016-May,2016,CY2016,...,N/A,14.0,3.7,5.53,0.50,2725,65400,2725,Each,True
2,988,2014-08-22,22,22,August,Aug,8,CY2014-Aug,2014,CY2014,...,N/A,7.0,18.0,26.91,0.25,1529,18348,1529,Carton,True
3,1375,2015-04-10,10,10,April,Apr,4,CY2015-Apr,2015,CY2015,...,N/A,7.0,18.0,26.91,0.25,2249,26988,2249,Carton,True
4,2010,2016-04-22,22,22,April,Apr,4,CY2016-Apr,2016,CY2016,...,N/A,7.0,18.0,26.91,0.40,3621,43452,3621,Carton,True
5,2028,2016-05-03,3,3,May,May,5,CY2016-May,2016,CY2016,...,N/A,14.0,3.7,5.53,0.50,2709,65016,2709,Each,True
6,752,2014-03-31,31,31,March,Mar,3,CY2014-Mar,2014,CY2014,...,N/A,7.0,18.0,26.91,0.25,1184,14208,1184,Carton,True
7,1117,2014-11-07,7,7,November,Nov,11,CY2014-Nov,2014,CY2014,...,N/A,7.0,18.0,26.91,0.35,785,9420,785,Carton,True
8,1128,2014-11-13,13,13,November,Nov,11,CY2014-Nov,2014,CY2014,...,N/A,14.0,3.5,5.23,0.30,409,10225,409,Each,True
9,1354,2015-03-28,28,28,March,Mar,3,CY2015-Mar,2015,CY2015,...,N/A,20.0,32.0,47.84,1.00,20,200,20,Each,True
10,1631,2015-09-10,10,10,September,Sep,9,CY2015-Sep,2015,CY2015,...,N/A,20.0,32.0,47.84,1.00,2380,23800,2380,Each,True
11,878,2014-06-14,14,14,June,Jun,6,CY2014-Jun,2014,CY2014,...,N/A,14.0,3.7,5.53,0.50,3,72,3,Each,True
12,219,2013-05-10,10,10,May,May,5,CY2013-May,2013,CY2013,...,N/A,7.0,18.0,26.91,0.40,340,4080,340,Carton,True
13,417,2013-09-05,5,5,September,Sep,9,CY2013-Sep,2013,CY2013,...,N/A,7.0,18.0,26.91,0.35,279,3348,279,Carton,True
14,1200,2014-12-26,26,26,December,Dec,12,CY2014-Dec,2014,CY2014,...,N/A,7.0,18.0,26.91,0.25,1908,22896,1908,Carton,True
15,1788,2015-12-14,14,14,December,Dec,12,CY2015-Dec,2015,CY2015,...,N/A,7.0,18.0,26.91,0.35,1499,17988,1499,Carton,True
16,285,2013-06-19,19,19,June,Jun,6,CY2013-Jun,2013,CY2013,...,N/A,7.0,18.0,26.91,0.25,376,4512,376,Carton,True
17,1277,2015-02-11,11,11,February,Feb,2,CY2015-Feb,2015,CY2015,...,N/A,20.0,32.0,47.84,1.00,1747,17470,1747,Each,True
18,2050,2016-05-17,17,17,May,May,5,CY2016-May,2016,CY2016,...,N/A,7.0,18.0,26.91,0.35,1784,21408,1784,Carton,True
19,1040,2014-09-23,23,23,September,Sep,9,CY2014-Sep,2014,CY2014,...,N/A,14.0,3.5,5.23,0.30,262,6550,262,Each,True

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 42 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Purchase Number                             20 non-null     int32
 1   Purchased  or Order Dates                   20 non-null     datetime64[us]
 2   Purchased  or Order Day Number              20 non-null     int32
 3   Purchased  or Order Day                     20 non-null     object
 4   Purchased  or Order Month Name              20 non-null     object
 5   Purchased  or Order Short Month Name        20 non-null     object
 6   Purchased  or Order Month Number            20 non-null     int32
 7   Purchased  or Order Calendar Month Name     20 non-null     object
 8   Purchased  or Order Year Number             20 non-null     int32
 9   Purchased  or Order Calendar Year Name      20 non-null     object
 10  Purchased  or Order Financial Month Number  20 non-null     int32
 11  Purchased  or Order Financial Month Name    20 non-null     object
 12  Purchased  or Order Financial Year          20 non-null     int32
 13  Purchased  or Order Financial Year Name     20 non-null     object
 14  Purchased  or Order Week Number             20 non-null     int32
 15  Supplier Code                               20 non-null     int32
 16  Supplier Name                               20 non-null     object
 17  Supplier Category                           20 non-null     object
 18  Primary Contact                             20 non-null     object
 19  Supplier Reference                          20 non-null     object
 20  Payment Days                                20 non-null     int32
 21  Postal Code                                 20 non-null     object
 22  Item ID                                     20 non-null     int32
 23  Item Name                                   20 non-null     object
 24  Item Color                                  20 non-null     object
 25  Item Selling Package                        20 non-null     object
 26  Item Buying Package                         20 non-null     object
 27  Item Brand                                  20 non-null     object
 28  Item Size                                   20 non-null     object
 29  ItemLead Time Days                          20 non-null     int32
 30  Item Quantity Per Outer                     20 non-null     int32
 31  Is Chiller Item                             20 non-null     bool
 32  Item Barcode                                20 non-null     object
 33  Item Tax Rate                               20 non-null     float64
 34  Item Unit Price                             20 non-null     float64
 35  Item Recommended Retail Price               20 non-null     float64
 36  Item Typical Weight Per Unit                20 non-null     float64
 37  Ordered Outers                              20 non-null     int32
 38  Ordered Quantity                            20 non-null     int32
 39  Received Outers                             20 non-null     int32
 40  Purchases Package                           20 non-null     object
 41  Is Purchases Finalized                      20 non-null     bool
dtypes: bool(2), datetime64[us](1), float64(4), int32(15), object(20)
memory usage: 5.2+ KB

In [30]:
Sale_Invoice = con.execute("SELECT * FROM Sale_Invoice limit 20").df()
display(Sale_Invoice)

,Invoice ID,City Code,City Name,State or Province,Country,Continent,Sales Territory,Region,Subregion,Latest Recorded Population in City,...,Packaging Type,Sale Quantity,Unit Price of Item,Tax Rate on Item,Total Excluding Tax on Invoice,Tax Amount on Item,Earned Profit on Invoice,Tax Amount on Invoice,Total Item can be stored in Dry Place,Total Item need stored in cooler or child Place
0,10103,26788,Philip,South Dakota,United States,North America,Plains,Americas,Northern America,779,...,Each,10,13.00,15.0,130.0,19.50,85.0,149.50,10,0
1,17860,20189,Lucasville,Ohio,United States,North America,Great Lakes,Americas,Northern America,2757,...,Each,6,32.00,15.0,192.0,28.80,120.0,220.80,6,0
2,28503,38038,Yermo,California,United States,North America,Far West,Americas,Northern America,0,...,Each,7,35.00,15.0,245.0,36.75,126.0,281.75,7,0
3,28479,9077,Dickworsham,Texas,United States,North America,Southwest,Americas,Northern America,0,...,Each,5,13.00,15.0,65.0,9.75,42.5,74.75,5,0
4,51827,25505,Optimo,New Mexico,United States,North America,Southwest,Americas,Northern America,0,...,Each,20,45.00,15.0,900.0,135.00,480.0,1035.00,20,0
5,64797,21351,Mayhill,New Mexico,United States,North America,Southwest,Americas,Northern America,75,...,Each,3,240.00,15.0,720.0,108.00,390.0,828.00,3,0
6,66257,6238,Cherryplain,New York,United States,North America,Mideast,Americas,Northern America,0,...,Each,70,18.00,15.0,1260.0,189.00,700.0,1449.00,70,0
7,16729,18772,Larose,Louisiana,United States,North America,Southeast,Americas,Northern America,7400,...,Each,8,230.00,15.0,1840.0,276.00,680.0,2116.00,8,0
8,34796,17054,Jessie,North Dakota,United States,North America,Plains,Americas,Northern America,25,...,Each,2,25.00,15.0,50.0,7.50,25.0,57.50,2,0
9,35683,26788,Philip,South Dakota,United States,North America,Plains,Americas,Northern America,779,...,Each,1,13.00,15.0,13.0,1.95,8.5,14.95,1,0
10,24585,20376,Lynne,Florida,United States,North America,Southeast,Americas,Northern America,0,...,Each,250,2.04,15.0,510.0,76.50,247.5,586.50,250,0
11,55446,37403,Wimbledon,North Dakota,United States,North America,Plains,Americas,Northern America,216,...,Each,4,35.00,15.0,140.0,21.00,72.0,161.00,4,0
12,60047,29729,Royal City,Washington,United States,North America,Far West,Americas,Northern America,2140,...,Each,1,13.00,15.0,13.0,1.95,8.5,14.95,1,0
13,45371,25646,Orrtanna,Pennsylvania,United States,North America,Mideast,Americas,Northern America,173,...,Each,4,230.00,15.0,920.0,138.00,340.0,1058.00,4,0
14,41222,38042,Yewed,Oklahoma,United States,North America,Southwest,Americas,Northern America,0,...,Each,10,13.00,15.0,130.0,19.50,85.0,149.50,10,0
15,67275,29158,Roberta Mill,North Carolina,United States,North America,Southeast,Americas,Northern America,0,...,Each,80,18.50,15.0,1480.0,222.00,580.0,1702.00,80,0
16,67520,31752,Skyway,Washington,United States,North America,Far West,Americas,Northern America,0,...,Each,50,1.05,15.0,52.5,7.88,25.0,60.38,50,0
17,57005,928,Antares,Arizona,United States,North America,Southwest,Americas,Northern America,126,...,Each,12,18.00,15.0,216.0,32.40,114.0,248.40,12,0
18,58246,18375,Lake Hughes,California,United States,North America,Far West,Americas,Northern America,649,...,Each,4,13.00,15.0,52.0,7.80,34.0,59.80,4,0
19,48229,21282,Mauldin,South Carolina,United States,North America,Southeast,Americas,Northern America,22889,...,Each,84,18.00,15.0,1512.0,226.80,924.0,1738.80,84,0

In [32]:
Sale_Invoice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 80 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Invoice ID                                       20 non-null     int32
 1   City Code                                        20 non-null     int32
 2   City Name                                        20 non-null     object
 3   State or Province                                20 non-null     object
 4   Country                                          20 non-null     object
 5   Continent                                        20 non-null     object
 6   Sales Territory                                  20 non-null     object
 7   Region                                           20 non-null     object
 8   Subregion                                        20 non-null     object
 9   Latest Recorded Population in City               20 non-null     int64
 10  Customer Code                                    20 non-null     int32
 11  Customer Full Name                               20 non-null     object
 12  Billing Customer Full Name                       20 non-null     object
 13  Customer Category                                20 non-null     object
 14  Customer Buying Group                            20 non-null     object
 15  Customer Primary Contact                         20 non-null     object
 16  Customer Postal Code                             20 non-null     object
 17  Billing Customer Code                            20 non-null     int32
 18  Billing Customer Full Name_1                     20 non-null     object
 19  Billing Customer Full Name_2                     20 non-null     object
 20  Billing Customer Category                        20 non-null     object
 21  Billing Customer Buying Group                    20 non-null     object
 22  Billing Customer Primary Contact                 20 non-null     object
 23  Billing Customer Postal Code                     20 non-null     object
 24  Item ID                                          20 non-null     int32
 25  Item Name                                        20 non-null     object
 26  Item Color                                       20 non-null     object
 27  Item Selling Package                             20 non-null     object
 28  Item Buying Package                              20 non-null     object
 29  Item Brand                                       20 non-null     object
 30  Item Size                                        20 non-null     object
 31  ItemLead Time Days                               20 non-null     int32
 32  Item Quantity Per Outer                          20 non-null     int32
 33  Is Chiller Item                                  20 non-null     bool
 34  Item Barcode                                     20 non-null     object
 35  Item Tax Rate                                    20 non-null     float64
 36  Item Unit Price                                  20 non-null     float64
 37  Item Recommended Retail Price                    20 non-null     float64
 38  Item Typical Weight Per Unit                     20 non-null     float64
 39  Invoice Dates                                    20 non-null     datetime64[us]
 40  Invoice Day Number                               20 non-null     int32
 41  Invoice Day                                      20 non-null     object
 42  Invoice Month Name                               20 non-null     object
 43  Invoice Short Month Name                         20 non-null     object
 44  Invoice Month Number                             20 non-null     int32
 45  Invoice Calendar Month Name                      20 non-null     object
 46  Invoice Year Number                              20 non-null     int32
 47  Invoice Calendar Year Name                       20 non-null     object
 48  Invoice Financial Month Number                   20 non-null     int32
 49  Invoice Financial Month Name                     20 non-null     object
 50  Invoice Financial Year                           20 non-null     int32
 51  Invoice Financial Year Name                      20 non-null     object
 52  Invoice Week Number                              20 non-null     int32
 53  Delivery Dates                                   20 non-null     datetime64[us]
 54  Delivery Day Number                              20 non-null     int32
 55  Delivery Day                                     20 non-null     object
 56  Delivery Month Name                              20 non-null     object
 57  Delivery Short Month Name                        20 non-null     object
 58  Delivery Month Number                            20 non-null     int32
 59  Delivery Calendar Month Name                     20 non-null     object
 60  Delivery Year Number                             20 non-null     int32
 61  Delivery Calendar Year Name                      20 non-null     object
 62  Delivery Financial Month Number                  20 non-null     int32
 63  Delivery Financial Month Name                    20 non-null     object
 64  Delivery Financial Year                          20 non-null     int32
 65  Delivery Financial Year Name                     20 non-null     object
 66  Delivery Week Number                             20 non-null     int32
 67  Employee Full Name                               20 non-null     object
 68  Employee Calling Name                            20 non-null     object
 69  Billing Note Description / Annotation            20 non-null     object
 70  Packaging Type                                   20 non-null     object
 71  Sale Quantity                                    20 non-null     int32
 72  Unit Price of Item                               20 non-null     float64
 73  Tax Rate on Item                                 20 non-null     float64
 74  Total Excluding Tax on Invoice                   20 non-null     float64
 75  Tax Amount on Item                               20 non-null     float64
 76  Earned Profit on Invoice                         20 non-null     float64
 77  Tax Amount on Invoice                            20 non-null     float64
 78  Total Item can be stored in Dry Place            20 non-null     int32
 79  Total Item need stored in cooler or child Place  20 non-null     int32
dtypes: bool(1), datetime64[us](2), float64(10), int32(22), int64(1), object(44)
memory usage: 10.8+ KB

In [34]:
sql = """
SELECT "Customer Full Name", SUM("Earned Profit on Invoice") AS Total_Profit FROM "Sale_Invoice" WHERE "Invoice Year Number" = 2016 GROUP BY "Invoice Month Name"
"""
print(sql)
output = con.execute(sql).df()
display(output)

SELECT "Customer Full Name", SUM("Earned Profit on Invoice") AS Total_Profit FROM "Sale_Invoice" WHERE "Invoice Year Number" = 2016 GROUP BY "Invoice Month Name"

BinderException: Binder Error: column "Customer Full Name" must appear in the GROUP BY clause or must be part of an aggregate function.
Either add it to the GROUP BY list, or use "ANY_VALUE(Customer Full Name)" if the exact value of "Customer Full Name" is not important.

LINE 2: SELECT "Customer Full Name", SUM("Earned Profit on Invoice") AS...
               ^

### Iceburg to SQLite

In [2]:
from pyspark.sql import functions as sf
from pyspark.sql import window as sw
from pyspark.sql import types as sdt
from pyspark.sql import SparkSession
from datetime import datetime

LOCAL_WAREHOUSE_PATH = "/data/data_files/iceberg/iceberg_warehouse"
STG_WAREHOUSE_PATH = "/data/data_files/iceberg/iceberg_staging_warehouse"
RPT_WAREHOUSE_PATH = "/data/data_files/iceberg/WideWorldImportersDW"

MSSQL_JAR = "C:/data/spark/jars/mssql-jdbc-12.6.5.jre11.jar"

CATALOG_NAME = "local"
STG_CATALOG_NAME = "staging"
WH_CATALOG_NAME = "reporting"

# staging_table_name = "staging.Integration.employee_Staging"
# wh_table_name = "reporting.dimension.Employees"

spark = SparkSession.builder \
    .appName("Iceberg Setup") \
    .config(f"spark.sql.catalog.{CATALOG_NAME}", "org.apache.iceberg.spark.SparkCatalog") \
    .config(f"spark.sql.catalog.{CATALOG_NAME}.catalog-impl", "org.apache.iceberg.hadoop.HadoopCatalog") \
    .config(f"spark.sql.catalog.{CATALOG_NAME}.warehouse", f"file:///{LOCAL_WAREHOUSE_PATH}") \
    .config(f"spark.sql.catalog.{STG_CATALOG_NAME}", "org.apache.iceberg.spark.SparkCatalog") \
    .config(f"spark.sql.catalog.{STG_CATALOG_NAME}.catalog-impl", "org.apache.iceberg.hadoop.HadoopCatalog") \
    .config(f"spark.sql.catalog.{STG_CATALOG_NAME}.warehouse", f"file:///{STG_WAREHOUSE_PATH}") \
    .config(f"spark.sql.catalog.{WH_CATALOG_NAME}", "org.apache.iceberg.spark.SparkCatalog") \
    .config(f"spark.sql.catalog.{WH_CATALOG_NAME}.catalog-impl", "org.apache.iceberg.hadoop.HadoopCatalog") \
    .config(f"spark.sql.catalog.{WH_CATALOG_NAME}.warehouse", f"file:///{RPT_WAREHOUSE_PATH}") \
    .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions") \
    .getOrCreate()


spark.catalog.setCurrentCatalog(WH_CATALOG_NAME)

spark
# spark.sql("SHOW CATALOGS").show(truncate=False)
# spark.sql("SHOW NAMESPACES IN reporting").show(truncate=False)
# spark.sql("SHOW DATABASES IN reporting").show(truncate=False)
# spark.sql("SHOW TABLES IN reporting.dimension").show(truncate=False)
for ns in spark.sql("SHOW NAMESPACES IN reporting").collect():
    namespace = ns["namespace"]
    # print(f"\nNamespace: {namespace}")
    spark.sql(f"SHOW TABLES IN reporting.{namespace}").show(truncate=False)

+---------+----------------+-----------+
|namespace|tableName       |isTemporary|
+---------+----------------+-----------+
|dimension|payment_method  |false      |
|dimension|supplier        |false      |
|dimension|city            |false      |
|dimension|stock_item      |false      |
|dimension|customer        |false      |
|dimension|date            |false      |
|dimension|transaction_type|false      |
|dimension|employee        |false      |
+---------+----------------+-----------+

+---------+-------------+-----------+
|namespace|tableName    |isTemporary|
+---------+-------------+-----------+
|fact     |purchase     |false      |
|fact     |stock_holding|false      |
|fact     |order        |false      |
|fact     |movement     |false      |
|fact     |sale         |false      |
|fact     |transaction  |false      |
+---------+-------------+-----------+

+-----------+-----------------------+-----------+
|namespace  |tableName              |isTemporary|
+-----------+-----------------------+-----------+
|integration|employee_staging       |false      |
|integration|transactiontype_staging|false      |
|integration|paymentmethod_staging  |false      |
|integration|supplier_staging       |false      |
|integration|movement_staging       |false      |
|integration|customer_staging       |false      |
|integration|city_staging           |false      |
|integration|stockholding_staging   |false      |
|integration|lineage                |false      |
|integration|order_staging          |false      |
|integration|stockitem_staging      |false      |
|integration|transaction_staging    |false      |
|integration|etl_cutoff             |false      |
|integration|sale_staging           |false      |
|integration|purchase_staging       |false      |
+-----------+-----------------------+-----------+

In [ ]:
import sqlite3
from pyspark.sql.types import DateType, TimestampType, TimestampNTZType, DecimalType
from pyspark.sql.functions import col

SQLITE_DB_PATH = "WideWorldImporters.db"

namespaces = [row["namespace"] for row in spark.sql("SHOW NAMESPACES IN reporting").collect()]

for ns in namespaces:
    tables = spark.sql(f"SHOW TABLES IN reporting.{ns}").collect()
    
    for t in tables:
        table_name = t["tableName"]
        full_iceberg_name = f"reporting.{ns}.{table_name}"
        sqlite_table_name = f"{ns}_{table_name}"
        
        print(f"Exporting {full_iceberg_name} -> {sqlite_table_name}...")
        
        # Read table
        df = spark.read.table(full_iceberg_name)
        
        # Cast dates, timestamps, and decimals to prevent Windows OS and sqlite3 binding errors
        for field in df.schema.fields:
            # Fix 1: Handle pre-1970/out-of-range dates on Windows
            if isinstance(field.dataType, (DateType, TimestampType, TimestampNTZType)):
                df = df.withColumn(field.name, col(field.name).cast("string"))
            
            # Fix 2: Handle DecimalType for SQLite binding
            # Use "double" for standard math/numeric support in SQLite
            # Use "string" if absolute financial precision is required
            elif isinstance(field.dataType, DecimalType):
                df = df.withColumn(field.name, col(field.name).cast("double"))
        
        # Safely convert to Pandas and export to SQLite
        pdf = df.toPandas()
        
        with sqlite3.connect(SQLITE_DB_PATH) as conn:
            pdf.to_sql(sqlite_table_name, conn, if_exists="replace", index=False)

print("Export to SQLite completed successfully!")

sqlite3.close

Exporting reporting.dimension.payment_method -> dimension_payment_method...
Exporting reporting.dimension.supplier -> dimension_supplier...
Exporting reporting.dimension.city -> dimension_city...
Exporting reporting.dimension.stock_item -> dimension_stock_item...
Exporting reporting.dimension.customer -> dimension_customer...
Exporting reporting.dimension.date -> dimension_date...
Exporting reporting.dimension.transaction_type -> dimension_transaction_type...
Exporting reporting.dimension.employee -> dimension_employee...
Exporting reporting.fact.purchase -> fact_purchase...
Exporting reporting.fact.stock_holding -> fact_stock_holding...
Exporting reporting.fact.order -> fact_order...
Exporting reporting.fact.movement -> fact_movement...
Exporting reporting.fact.sale -> fact_sale...
Exporting reporting.fact.transaction -> fact_transaction...
Exporting reporting.integration.employee_staging -> integration_employee_staging...
Exporting reporting.integration.transactiontype_staging -> integration_transactiontype_staging...
Exporting reporting.integration.paymentmethod_staging -> integration_paymentmethod_staging...
Exporting reporting.integration.supplier_staging -> integration_supplier_staging...
Exporting reporting.integration.movement_staging -> integration_movement_staging...
Exporting reporting.integration.customer_staging -> integration_customer_staging...
Exporting reporting.integration.city_staging -> integration_city_staging...
Exporting reporting.integration.stockholding_staging -> integration_stockholding_staging...
Exporting reporting.integration.lineage -> integration_lineage...
Exporting reporting.integration.order_staging -> integration_order_staging...
Exporting reporting.integration.stockitem_staging -> integration_stockitem_staging...
Exporting reporting.integration.transaction_staging -> integration_transaction_staging...
Exporting reporting.integration.etl_cutoff -> integration_etl_cutoff...
Exporting reporting.integration.sale_staging -> integration_sale_staging...
Exporting reporting.integration.purchase_staging -> integration_purchase_staging...
Export to SQLite completed successfully!

In [6]:
import os

db_filename = "WideWorldImporters.db"
absolute_path = os.path.abspath(db_filename)

print("SQLite DB Full Path:", absolute_path)

SQLite DB Full Path: c:\data\repository_git\WideWorldImporters.db

In [7]:
spark.stop()

In [2]:
import sqlite3

SQLITE_DB_PATH = r"C:\Users\progr\Downloads\WideWorldImporters.db"

with sqlite3.connect(SQLITE_DB_PATH) as conn:
    cursor = conn.cursor()
    
    # Query sqlite_master for all table names
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;")
    tables = cursor.fetchall()
    
    print(f"Total Tables Found: {len(tables)}\n" + "-"*35)
    for t in tables:
        table_name = t[0]
        # Get row count for each table
        cursor.execute(f"SELECT COUNT(*) FROM {table_name}")
        row_count = cursor.fetchone()[0]
        print(f"• {table_name:<30} ({row_count:,} rows)")

Total Tables Found: 29
-----------------------------------
• dimension_city                 (116,295 rows)
• dimension_customer             (403 rows)
• dimension_date                 (1,461 rows)
• dimension_employee             (213 rows)
• dimension_payment_method       (6 rows)
• dimension_stock_item           (672 rows)
• dimension_supplier             (28 rows)
• dimension_transaction_type     (15 rows)
• fact_movement                  (236,667 rows)
• fact_order                     (231,412 rows)
• fact_purchase                  (8,367 rows)
• fact_sale                      (228,265 rows)
• fact_stock_holding             (227 rows)
• fact_transaction               (99,585 rows)
• integration_city_staging       (0 rows)
• integration_customer_staging   (0 rows)
• integration_employee_staging   (0 rows)
• integration_etl_cutoff         (28 rows)
• integration_lineage            (26 rows)
• integration_movement_staging   (0 rows)
• integration_order_staging      (0 rows)
• integration_paymentmethod_staging (0 rows)
• integration_purchase_staging   (0 rows)
• integration_sale_staging       (0 rows)
• integration_stockholding_staging (0 rows)
• integration_stockitem_staging  (0 rows)
• integration_supplier_staging   (0 rows)
• integration_transaction_staging (0 rows)
• integration_transactiontype_staging (0 rows)

In [7]:
import sqlite3
import pandas as pd

SQLITE_DB_PATH = r"C:\Users\progr\Downloads\WideWorldImporters.db"

with sqlite3.connect(SQLITE_DB_PATH) as conn:
    # 1. Read table into a Pandas DataFrame
    df_orders = pd.read_sql_query("SELECT * FROM fact_order LIMIT 5", conn)
    print("--- First 5 Orders ---")
    print(df_orders.head())

    # 2. Perform a JOIN directly in SQL and load result into DataFrame
    join_query = """
    SELECT 
        o.OrderID,
        o.OrderDateKey,
        c.Customer,
        o.TotalIncludingTax
    FROM fact_order o
    LEFT JOIN dimension_customer c ON o.CustomerKey = c.CustomerKey
    LIMIT 10
    """
    df_order_customers = pd.read_sql_query(join_query, conn)
    
    print("\n--- Order & Customer Joined DataFrame ---")
    print(df_order_customers)

--- First 5 Orders ---
   Order_Key  City_Key  Customer_Key  Stock_Item_Key Order_Date_Key  \
0     173549    107539           256             163     2015-08-12
1     185445     44986            71              29     2015-10-12
2      35034     87673           223              69     2013-07-23
3      20318     44701           241             196     2013-05-03
4     161528     80875             0              11     2015-06-15

  Picked_Date_Key  Salesperson_Key  Picker_Key  WWI_Order_ID  \
0      2015-08-12              152           0         55018
1      2015-10-12              155           0         58830
2      2013-07-23               39           0         11020
3      2013-05-03               61           0          6374
4      2015-06-15              145           0         51159

   WWI_Backorder_ID                                        Description  \
0           55095.0  IT joke mug - hardware: part of the computer t...
1           58888.0    Black and orange fragile despatch tape 48mmx75m
2           11101.0                   Pack of 12 action figures (male)
3            6385.0     DBA joke mug - I will get you in order (White)
4           51212.0  Packing knife with metal insert blade (Yellow)...

  Package  Quantity  Unit_Price  Tax_Rate  Total_Excluding_Tax  Tax_Amount  \
0    Each         4       13.00      15.0                 52.0        7.80
1    Each       144        3.70      15.0                532.8       79.92
2  Packet         1       16.00      15.0                 16.0        2.40
3    Each         7       13.00      15.0                 91.0       13.65
4    Each        10        1.89      15.0                 18.9        2.84

   Total_Including_Tax  Lineage_Key
0                59.80            9
1               612.72            9
2                18.40            9
3               104.65            9
4                21.74            9

DatabaseError: Execution failed on sql '
    SELECT
        o.OrderID,
        o.OrderDateKey,
        c.Customer,
        o.TotalIncludingTax
    FROM fact_order o
    LEFT JOIN dimension_customer c ON o.CustomerKey = c.CustomerKey
    LIMIT 10
    ': no such column: o.OrderID

In [8]:
from pyspark.sql import SparkSession

# Ensure you specify the path to your sqlite-jdbc jar
SQLITE_JAR = "C:/data/spark/jars/sqlite-jdbc-3.45.1.0.jar"  # Adjust path to your jar location

# 1. Initialize or get the existing SparkSession
spark = SparkSession.builder \
    .appName("SQLite Reader") \
    .config("spark.jars", SQLITE_JAR) \
    .getOrCreate()

# 2. Now run your SQLite JDBC code safely
SQLITE_DB_PATH = r"C:\Users\progr\Downloads\WideWorldImporters.db"
jdbc_url = f"jdbc:sqlite:{SQLITE_DB_PATH}"

df_fact_order = spark.read \
    .format("jdbc") \
    .option("url", jdbc_url) \
    .option("dbtable", "fact_order") \
    .option("driver", "org.sqlite.JDBC") \
    .load()

df_dim_customer = spark.read \
    .format("jdbc") \
    .option("url", jdbc_url) \
    .option("dbtable", "dimension_customer") \
    .option("driver", "org.sqlite.JDBC") \
    .load()

# Join DataFrames
df_joined = df_fact_order.join(
    df_dim_customer, 
    on="CustomerKey", 
    how="left"
).select(
    "OrderID", 
    "OrderDateKey", 
    "Customer", 
    "TotalIncludingTax"
)

df_joined.show(5, truncate=False)

PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.

In [ ]:
import sqlite3

SQLITE_DB_PATH = "WideWorldImporters.db"

# Define your SQL view creation query
CREATE_VIEW_SQL = """
CREATE VIEW IF NOT EXISTS v_customer_sales_summary AS
SELECT
"""

with sqlite3.connect(SQLITE_DB_PATH) as conn:
    cursor = conn.cursor()
    
    # 1. Create the view
    cursor.execute(CREATE_VIEW_SQL)
    print("View 'v_customer_sales_summary' created successfully!\n")
    
    # 2. Query data directly from the newly created view
    cursor.execute("SELECT * FROM v_customer_sales_summary LIMIT 5;")
    results = cursor.fetchall()
    
    # Display results
    print("Sample Output from View:")
    for row in results:
        print(row)